// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyCTLlAnGoz932viEbrTh0N8qAdiJHLAJGE',
    appId: '1:483932268453:android:60ae27b1630291868aea4c',
    messagingSenderId: '483932268453',
    projectId: 'workitpt-dev',
    storageBucket: 'workitpt-dev.appspot.com',
  );

  static const FirebaseOptions androidRelease = FirebaseOptions(
    apiKey: 'AIzaSyBiJ8GuLLCqCS9yQtl1tldoZFkdTBSyGYA',
    appId: '1:470549648120:android:7746fe2c6b13506364610d',
    messagingSenderId: '470549648120',
    projectId: 'workitpt-21452',
    storageBucket: 'workitpt-21452.appspot.com',
  );

  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyAmFkPcnsFPArVKTDKYqbOFsQ6O0_rzysI',
    appId: '1:483932268453:ios:de74b850a74404bb8aea4c',
    messagingSenderId: '483932268453',
    projectId: 'workitpt-dev',
    storageBucket: 'workitpt-dev.appspot.com',
    androidClientId:
        '483932268453-4tj13kg536vaa5mn0psqi2q3ikgohfrt.apps.googleusercontent.com',
    iosClientId:
        '483932268453-54d5tq2j7mic85i6i2ttttikeonjqrnf.apps.googleusercontent.com',
    iosBundleId: 'com.app.workitpt',
  );

  static const FirebaseOptions iosRelease = FirebaseOptions(
    apiKey: 'AIzaSyD-LFbYOCu3mb-q9iahfPVZlN3Rab7JNHY',
    appId: '1:470549648120:ios:fa4af252f7f1a6eb64610d',
    messagingSenderId: '470549648120',
    projectId: 'workitpt-21452',
    storageBucket: 'workitpt-21452.appspot.com',
    androidClientId:
        '470549648120-v0g9rklnes2kf74lqjp7vurtgu614d2t.apps.googleusercontent.com',
    iosClientId:
        '470549648120-r4ejt2far35kd3uqjib6bfuu3oagfb59.apps.googleusercontent.com',
    iosBundleId: 'com.app.workitpt',
  );

  static FirebaseOptions get devCurrentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidDev;
      case TargetPlatform.iOS:
        return iosDev;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get releaseCurrentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidRelease;
      case TargetPlatform.iOS:
        return iosRelease;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Future<FirebaseOptions> getFlavor() async {
  //   final  flavor =
  //   await const MethodChannel('flavor').invokeMethod('getFlavor');
  //
  //   if(defaultTargetPlatform==TargetPlatform.android){
  //     if(flavor == Environment.dev){
  //       return androidDev;
  //     }else if(flavor == Environment.prod){
  //       return androidRelease;
  //     }else{
  //       return androidRelease;
  //     }
  //   }else if(defaultTargetPlatform==TargetPlatform.iOS){
  //     if(flavor == Environment.dev){
  //       return iosDev;
  //     }else if(flavor == Environment.prod){
  //       return iosRelease;
  //     }else{
  //       return iosRelease;
  //     }
  //   }else{
  //     return androidRelease;
  //   }
}
